### PR TITLE
faster loading of illustration detail fragment during swipes

### PR DESCRIPTION
**Pull request by manishxshrestha**
On PictureXFragment, extending class Fragment instead of LazyV4Fragment, fragments are loaded during swipes instead of loading after swipe is complete.
In the original app, for me, the user experience is ruined a bit because when i swipe right, page is blank and takes a little bit of time to load. Extending fragment class loads the fragment so I can  see the illustration detail even when the image is not loaded.

### CODE REVIEW

**Comment by Notsfsssf** [comment]
The purpose of this ‘LazyV4Fragment’ is to open an illust page without loading data immediately in right or left page，so it will not cause more UI binding and loading.I just want to know why you said your method is more memory saving,no memory leaks and gc?:(

**Comment by manishxshrestha** [comment]
um, LazyV4Fragment will not cause more UI binding and loading but there is no smooth transition when swiped left and right. It feels a little bit clunky. There might be more memory leaks and gc but android profiler shows memory usage in between 200-500mb on images. I just think its necessary tradeoff for smooth user experience.

**Comment by manishxshrestha** [comment]
If this pull request is not good then should i send another request for for search tag that shows name along with its translated name

image

**Comment by Notsfsssf** [comment]
I think I should stick to the original method.

**Comment by tekoki** [comment]
Hello, I am Chinese, did you send the mail to the wrong place?




------------------&nbsp;Original&nbsp;------------------

**Comment by Notsfsssf** [comment]
@tekoki 你是接到了谁的邮件转发

**Comment by tekoki** [comment]
好多人的，请问你是...




------------------&nbsp;Original&nbsp;------------------

**Comment by Notsfsssf** [comment]
你应该是来错地方了，这里是我项目的issue

**Comment by tekoki** [comment]
hello i am Chinese, i am just a newbie, are you a person in flesh?or a robot?




------------------&nbsp;Original&nbsp;------------------

**Comment by tekoki** [comment]
等等，我想弄清楚一下，我只是个新手，我现在还没搞清楚我的情况，我是在我的QQ邮箱里面接受到许多的邮件，是关于github的，我刚刚开始玩github,你可以解释一下啊这个是什么情况吗,我觉得我没来错地方，话说你是群主吗，p站图片批量下载器的那个群



------------------&nbsp;Original&nbsp;------------------

**Comment by Notsfsssf** [comment]
@tekoki 你应该是watch了我的项目或者subscribe了这个issue    
  

你需要在这两个地方unwatch unsubscribe，就不会接到这些邮件了，这不是我们造成的，而是你自己关注造成的

**Comment by Notsfsssf** [comment]
@tekoki 如果搞明白了，或者没搞明白也没关系，自己google一下github watch和subscribe的作用，这本身是你自己设置的问题，我要删除这些无用的内容了，如果你还持续在我项目上的issue发无用内容，影响到其他正常反馈或者提交贡献的人，我会直接block你

**Pull request closed without merging**
